Add nifty make check rule to check that all of the icons are listed in the
2006-11-09  Rodney Dawes  <dobey@novell.com>

	* */*/Makefile.am: Add nifty make check rule to check that all of the
	icons are listed in the Makefile.am to help prevent missing icons

diff --git a/22x22/places/Makefile.am b/22x22/places/Makefile.am
--- a/22x22/places/Makefile.am
+++ b/22x22/places/Makefile.am
@@ -22,3 +22,21 @@ EXTRA_DIST =		\
 install-data-local: install-iconsDATA
 	(cd $(DESTDIR)$(themedir)/$(size) && $(ICONMAP) -c $(context))
 
+check:
+	if test -r CVS/Entries; then \
+		for icon in *.png; do \
+			if grep $$icon CVS/Entries > /dev/null; then \
+				if ! grep $$icon Makefile > /dev/null; then \
+					echo "Missing $$icon in Makefile.am"; \
+					exit 1; \
+				fi; \
+			fi; \
+		done; \
+	else \
+		for icon in *.png; do \
+			if ! grep $$icon Makefile > /dev/null; then \
+				echo "Missing $$icon in Makefile.am"; \
+				exit 1; \
+			fi; \
+		done; \
+	fi
diff --git a/24x24/filesystems/Makefile.am b/24x24/filesystems/Makefile.am
--- a/24x24/filesystems/Makefile.am
+++ b/24x24/filesystems/Makefile.am
@@ -12,3 +12,22 @@ EXTRA_DIST =		\
 
 MAINTAINERCLEANFILES =	\
 	Makefile.in
+
+check:
+	if test -r CVS/Entries; then \
+		for icon in *.png; do \
+			if grep $$icon CVS/Entries > /dev/null; then \
+				if ! grep $$icon Makefile > /dev/null; then \
+					echo "Missing $$icon in Makefile.am"; \
+					exit 1; \
+				fi; \
+			fi; \
+		done; \
+	else \
+		for icon in *.png; do \
+			if ! grep $$icon Makefile > /dev/null; then \
+				echo "Missing $$icon in Makefile.am"; \
+				exit 1; \
+			fi; \
+		done; \
+	fi
